version: '3.4'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

  rich-puppeteer:
    image: damoeb/rich-rss:puppeteer-0.1
    restart: always
    security_opt:
      - seccomp=./docker/chrome.json
    networks:
      - puppeteer

  rss-proxy:
    image: damoeb/rss-proxy:2
    restart: always
#    healthcheck:
#      test: curl --fail http://localhost:8080/health || exit 1
#      interval: 10s
#      retries: 3
#      start_period: 10s
#      timeout: 10s

    depends_on:
      - rich-puppeteer
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
      - TOKEN_SECRET=1234_top_secret
      - APP_PUBLIC_URL=http://localhost:8080
      - PUPPETEER_HOST=http://rich-puppeteer:3000
      - spring_profiles_active=monitoring
    secrets:
      - TOKEN_SECRET
    networks:
      - puppeteer
      - loki


  # ----------------------------------------------------------------------------------------------------------------------
  # -- MONITORING
  # ----------------------------------------------------------------------------------------------------------------------

  loki:
    image: grafana/loki:2.5.0
    volumes:
      - ./docker/loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    #    container_name: grafana-service
    ports:
      - "3000:3000"
    networks:
      - loki

# https://www.baeldung.com/ops/docker-secrets
secrets:
  TOKEN_SECRET:
    file: ./tokenSecret.txt

networks:
  puppeteer:
    driver: bridge
  loki:
    driver: bridge
