version: '3.4'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

  rich-puppeteer:
    image: damoeb/rich-rss:puppeteer
    restart: always
    security_opt:
      - seccomp=./chrome.json
    networks:
      - puppeteer_net

  rss-proxy:
    image: damoeb/rss-proxy:2
    restart: always
#    healthcheck:
#      test: curl --fail http://localhost:8080/health || exit 1
#      interval: 10s
#      retries: 3
#      start_period: 10s
#      timeout: 10s

    depends_on:
      - rich-puppeteer
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
      - TOKEN_SECRET=1234_top_secret
      - APP_PUBLIC_URL=http://localhost:8080
      - PUPPETEER_HOST=http://rich-puppeteer:3000
    secrets:
      - TOKEN_SECRET
    networks:
      - puppeteer_net

# https://www.baeldung.com/ops/docker-secrets
secrets:
  TOKEN_SECRET:
    file: ./tokenSecret.txt

networks:
  puppeteer_net:
    driver: bridge
